### ISSUE TITLE
API name and URL change

### ISSUE THREAD

**Issue by booyaa** [zeyla/darksky.rs#1]
Hi,

forecast.io is now darksky.net. I forked your crate and have tested it's an easy fix. Ready to send a PR if you're interested.

Did you want to change the crate name too?

Here's the blog post announcing the name change: http://status.darksky.net/2016/09/20/forecast-api-is-now-dark-sky-api.html

**Comment by zeyla** [comment]
Sure, I'll accept a PR for it, thanks.

Yes, the crate name itself should probably be changed as well to avoid future confusion.

**Comment by zeyla** [comment]
Closed by #2.
