### ISSUE TITLE
Support historical weather requests

### ISSUE THREAD

**Issue by mklein994** [zeyla/darksky.rs#7]
Relevant docs: https://darksky.net/dev/docs#time-machine-request

The request is almost the same as a normal forecast request, it just has a date. From the docs: <pre>`https://api.darksky.net/forecast/[key]/[latitude],[longitude],`**[time]**</pre>

The [chrono](https://crates.io/crates/chrono) crate might help here.

**Comment by zeyla** [comment]
[Added](https://github.com/zeyla/darksky.rs/commit/069410baa032e4587273f9a87db81c9ff755e7a0) as a `get_forecast_time_machine` function on the hyper and reqwest client implementations, and published as v0.8.0 on crates.io.

**Comment by mklein994** [comment]
Wow, this feature is very modular, while not even using Chrono. Nice work! I could learn from this.
